M48
; DRILL file {KiCad 7.0.5} date Tue 20 Jun 2023 08:56:49 AM EDT
; FORMAT={2:4/ absolute / inch / keep zeros}
; #@! TF.CreationDate,2023-06-20T08:56:49-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X115992Y-040144
X115992Y-042053
T2
X117185Y-040026
X117185Y-042171
T0
M30
